name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: docker build -t myapp:${{ github.sha }} .

      # SERVIDOR SIMULADO
      - name: Create fake server
        run: mkdir -p fake_server

      - name: Copy docker-compose.yml
        run: cp docker-compose.yml fake_server/

      - name: Copy project files to fake server
        run: cp -R . fake_server/

      - name: Deploy (simulate docker compose up)
        run: |
          cd fake_server
          docker compose up -d --build

      - name: Show running containers
        run: docker ps
